name: Build QMK Firmware

description: Build QMK firmware from source

inputs:
  keyboard:
    description: The target keyboard for this firmware build
    required: true
  keymap:
    description: The keymap to build for this firmware
    required: true
    default: default
  output-dir:
    description: Directory in the workspace where built firmware will be placed
    default: qmk-output

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.keyboard }}
    - ${{ inputs.keymap }}
    - ${{ inputs.output-dir }}
