name: Build QMK Firmware

description: Build QMK firmware from source

branding:
  icon: box
  color: blue

inputs:
  keyboard:
    description: The target keyboard for this firmware build
    required: true
  keymap:
    description: The keymap to build for this firmware
    required: true
    default: default
  controller:
    description: The controller to build for this firmware
    required: false
  local-keymap-path:
    description: Path to a local keymap directory to inject into the QMK home
    default: ""
  output-dir:
    description: Directory in the workspace where built firmware will be placed
    default: qmk-output

outputs:
  built-images:
    description: A comma separated list of files copied to the output directory

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.keyboard }}
    - ${{ inputs.keymap }}
    - ${{ inputs.controller }}
    - ${{ inputs.output-dir }}
    - ${{ inputs.local-keymap-path }}
