name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build DZ65 RGB v3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@feat/add-first-implementation
        with:
          keyboard: dztech/dz65rgb/v3
          keymap: testing-keymap
          local-keymap-path: test/keymaps/testing-keymap
